name: '.NET - Build Service'
description: 'Builds a .NET service'   
author: 'Me'
inputs:
  solution-directory:
    description: 'Directory the .NET solution is contained in.'
    required: true
  dotnet-version:
    description: 'Versions of .NET to setup'
    required: true
  service-project:
    description: 'Location of the service project to build.'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-dotnet@v3
      if: inputs.dotnet-version != ''
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore Solution
      working-directory: ${{ inputs.solution-directory }}
      shell: bash
      run: |
        dotnet restore

    - name: Build - Service Projects
      working-directory: ${{ inputs.solution-directory }}
      if: inputs.service-project != ''
      shell: bash
      run: |
        dotnet build ${{ inputs.service-project }} -c 'Release' -p 'any'

    - name: Build - Solution
      working-directory: ${{ inputs.solution-directory }}
      shell: bash
      run: |
        dotnet restore
        dotnet build -c 'Release' -p 'any'